package com.company.ems.backend.common.constant;

public enum AppPermission {
    EMPLOYEE_VIEW,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,
    EMPLOYEE_IMPORT,
    EMPLOYEE_EXPORT,

    ATTENDANCE_READ,
    ATTENDANCE_CHECKIN,
    ATTENDANCE_ADJUSTMENT_REQUEST,
    ATTENDANCE_ADJUSTMENT_APPROVE,
    ATTENDANCE_ADJUSTMENT_ADMIN,

    LEAVE_VIEW,
    LEAVE_CREATE,
    LEAVE_APPROVE,
    LEAVE_CANCEL,
    LEAVE_BALANCE_READ,
    ASSET_MANAGE,
    AUDIT_LOG_VIEW,
    SYSTEM_CONFIG_MANAGE;

    public String key() {
        return this.name();
    }
}