import { LeaveResponseDTO } from "./leaveService";
import {
  AdjustmentRequestSummary,
  AdjustmentRequestDetail,
} from "./attendanceService";
import { AdminIncidentListItem, IncidentReportDetail } from "./assetService";

export const MOCK_LEAVE_REQUESTS: LeaveResponseDTO[] = [
  {
    id: 101,
    employeeId: 1,
    employeeName: "Nguyễn Văn A",
    leaveType: "ANNUAL",
    startDate: "2026-03-25",
    endDate: "2026-03-27",
    duration: 3,
    reason: "Đi du lịch cùng gia đình",
    status: "PENDING_LEVEL_1",
    attachmentUrl: null,
    createdAt: "2026-03-20T08:00:00",
  },
  {
    id: 102,
    employeeId: 2,
    employeeName: "Trần Thị B",
    leaveType: "SICK",
    startDate: "2026-03-22",
    endDate: "2026-03-22",
    duration: 1,
    reason: "Sốt cao, cần nghỉ ngơi",
    status: "PENDING_LEVEL_1",
    attachmentUrl: null,
    createdAt: "2026-03-20T09:15:00",
  },
  {
    id: 103,
    employeeId: 3,
    employeeName: "Lê Văn C",
    leaveType: "PERSONAL",
    startDate: "2026-03-30",
    endDate: "2026-03-30",
    duration: 1,
    reason: "Giải quyết việc gia đình riêng",
    status: "PENDING_LEVEL_1",
    attachmentUrl: null,
    createdAt: "2026-03-19T14:30:00",
  },
  {
    id: 104,
    employeeId: 4,
    employeeName: "Phạm Văn D",
    leaveType: "UNPAID",
    startDate: "2026-04-01",
    endDate: "2026-04-05",
    duration: 5,
    reason: "Nghỉ phép không lương để học tập",
    status: "PENDING_LEVEL_1",
    attachmentUrl: null,
    createdAt: "2026-03-18T10:00:00",
  },
];

export const MOCK_ADJUSTMENT_REQUESTS: AdjustmentRequestSummary[] = [
  {
    id: 201,
    employeeId: 1,
    employeeName: "Nguyễn Văn A",
    employeeCode: "EMP001",
    requestDate: "2026-03-19",
    proposedCheckInTime: "2026-03-19T08:00:00",
    proposedCheckOutTime: "2026-03-19T17:30:00",
    reasonType: "FORGOT_CHECKIN",
    reasonText: "Quên check-in buổi sáng do vội họp",
    status: "PENDING_LEVEL_1",
    currentApprovalLevel: 1,
    maxApprovalLevel: 2,
    createdAt: "2026-03-19T18:00:00",
  },
  {
    id: 202,
    employeeId: 5,
    employeeName: "Hoàng Văn E",
    employeeCode: "EMP005",
    requestDate: "2026-03-18",
    proposedCheckInTime: "2026-03-18T08:15:00",
    proposedCheckOutTime: "2026-03-18T17:45:00",
    reasonType: "DEVICE_ERROR",
    reasonText: "Thiết bị chấm công bị lỗi không nhận diện",
    status: "PENDING_LEVEL_1",
    currentApprovalLevel: 1,
    maxApprovalLevel: 1,
    createdAt: "2026-03-18T19:00:00",
  },
];

export const MOCK_ADJUSTMENT_DETAILS: Record<number, AdjustmentRequestDetail> =
  {
    201: {
      ...(MOCK_ADJUSTMENT_REQUESTS[0] as AdjustmentRequestSummary),
      attendanceId: null,
      incidentGeoLog: "10.762622, 106.660172",
      incidentPhotoUrl: "https://picsum.photos/seed/adj1/400/300",
      requiresManualReview: true,
      resolvedAt: null,
      resolvedByName: null,
      history: [
        {
          id: 1,
          actionByName: "Nguyễn Văn A",
          actionByUserId: 1,
          action: "CREATED",
          levelActedOn: null,
          comment: "Gửi yêu cầu điều chỉnh",
          actionAt: "2026-03-19T18:00:00",
          statusBefore: null,
          statusAfter: "PENDING_LEVEL_1",
        },
      ],
    },
    202: {
      ...(MOCK_ADJUSTMENT_REQUESTS[1] as AdjustmentRequestSummary),
      attendanceId: null,
      incidentGeoLog: "10.762622, 106.660172",
      incidentPhotoUrl: "https://picsum.photos/seed/adj2/400/300",
      requiresManualReview: true,
      resolvedAt: null,
      resolvedByName: null,
      history: [
        {
          id: 2,
          actionByName: "Hoàng Văn E",
          actionByUserId: 5,
          action: "CREATED",
          levelActedOn: null,
          comment: "Báo lỗi thiết bị",
          actionAt: "2026-03-18T19:00:00",
          statusBefore: null,
          statusAfter: "PENDING_LEVEL_1",
        },
      ],
    },
  };

export const MOCK_ASSET_REPORTS: AdminIncidentListItem[] = [
  {
    id: 301,
    reportId: "INC-2026-001",
    asset: "MacBook Pro M3 - Gold",
    employeeName: "Nguyễn Văn A",
    issueType: "DAMAGED",
    issueTypeLabel: "Hư hỏng",
    reportedAt: "2026-03-20",
    status: "PENDING",
    statusLabel: "Chờ duyệt",
    statusColor: "bg-amber-100 text-amber-700",
    requesterUserId: 1,
  },
  {
    id: 302,
    reportId: "INC-2026-002",
    asset: "Dell Precision 5570",
    employeeName: "Trần Thị B",
    issueType: "LOST",
    issueTypeLabel: "Thất lạc",
    reportedAt: "2026-03-19",
    status: "PENDING",
    statusLabel: "Chờ duyệt",
    statusColor: "bg-amber-100 text-amber-700",
    requesterUserId: 2,
  },
];

export const MOCK_ASSET_REPORT_DETAILS: Record<number, IncidentReportDetail> = {
  301: {
    id: 301,
    reportId: "INC-2026-001",
    asset: "MacBook Pro M3 - Gold",
    assetCode: "ASSET-001",
    assetTag: "LAPTOP",
    incidentType: "DAMAGED",
    incidentTypeLabel: "Hư hỏng",
    description:
      "Màn hình bị sọc sau khi vô tình để máy trong balo bị ép mạnh.",
    attachmentUrl: "https://picsum.photos/seed/asset1/800/600",
    status: "PENDING",
    statusLabel: "Chờ duyệt",
    statusColor: "bg-amber-100 text-amber-700",
    reportedBy: "Nguyễn Văn A",
    reportedAt: "2026-03-20 08:30",
    processedBy: null,
    processedAt: null,
    processNote: null,
    assetCondition: "GOOD",
    assetStatus: "ASSIGNED",
    requesterUserId: 1,
  },
  302: {
    id: 302,
    reportId: "INC-2026-002",
    asset: "Dell Precision 5570",
    assetCode: "ASSET-005",
    assetTag: "LAPTOP",
    incidentType: "LOST",
    incidentTypeLabel: "Thất lạc",
    description: "Để máy ở quán cafe và bị kẻ gian lấy mất.",
    attachmentUrl: null,
    status: "PENDING",
    statusLabel: "Chờ duyệt",
    statusColor: "bg-amber-100 text-amber-700",
    reportedBy: "Trần Thị B",
    reportedAt: "2026-03-19 18:45",
    processedBy: null,
    processedAt: null,
    processNote: null,
    assetCondition: "GOOD",
    assetStatus: "ASSIGNED",
    requesterUserId: 2,
  },
};
