package com.company.ems.backend.auditlog.enums;

/**
 * Audit Log Action Types adhering to standardized prefix rules.
 * Prefixes: AUTH_, DATA_, WORKFLOW_, SECURITY_, SYSTEM_
 */
public enum AuditActionType {

    // --- AUTH ---
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILED,
    AUTH_LOGOUT,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_REFRESH_SUCCESS,
    AUTH_TOKEN_REFRESH_FAILED,
    AUTH_TOKEN_REVOKED,
    AUTH_TOKEN_INVALID,

    // --- SECURITY ---
    SECURITY_ACCESS_DENIED,
    SECURITY_UNAUTHORIZED,
    SECURITY_RATE_LIMIT_EXCEEDED,
    SECURITY_SUSPICIOUS_ACTIVITY,

    // --- SYSTEM ---
    SYSTEM_SESSION_TIMEOUT,
    SYSTEM_FORCE_LOGOUT,
    SYSTEM_PASSWORD_CHANGED,

    // --- DATA ---
    DATA_CREATE_EMPLOYEE,
    DATA_UPDATE_EMPLOYEE,
    DATA_DELETE_EMPLOYEE,
    DATA_IMPORT_EMPLOYEE,
    DATA_EXPORT_EMPLOYEE,
    DATA_UPDATE_NATIONAL_ID,
    DATA_UPDATE_SALARY,
    DATA_UPDATE_BANK_INFO,
    DATA_UPDATE_CONTRACT,

    // --- WORKFLOW ---
    WORKFLOW_APPROVE_LEAVE,
    WORKFLOW_REJECT_LEAVE,
    WORKFLOW_ADJUST_ATTENDANCE,
    WORKFLOW_ASSET_REPORT_SUBMITTED,
    WORKFLOW_ASSET_REPORT_APPROVED,
    WORKFLOW_ASSET_REPORT_REJECTED
}
