INSERT INTO salary_components (
    created_at,
    updated_at,
    created_by,
    updated_by,
    version,
    deleted_at,
    is_deleted,
    deleted_by,
    code,
    name,
    type,
    is_taxable,
    is_insurable,
    amount,
    rate_percent,
    nature,
    status
)
VALUES
    (
        NOW(6),
        NOW(6),
        'SYSTEM',
        'SYSTEM',
        0,
        NULL,
        FALSE,
        NULL,
        'BHXH',
        'Bảo hiểm xã hội',
        'INSURANCE',
        FALSE,
        FALSE,
        NULL,
        8.0000,
        'DEDUCTION',
        'ACTIVE'
    ),
    (
        NOW(6),
        NOW(6),
        'SYSTEM',
        'SYSTEM',
        0,
        NULL,
        FALSE,
        NULL,
        'BHYT',
        'Bảo hiểm y tế',
        'INSURANCE',
        FALSE,
        FALSE,
        NULL,
        1.5000,
        'DEDUCTION',
        'ACTIVE'
    ),
    (
        NOW(6),
        NOW(6),
        'SYSTEM',
        'SYSTEM',
        0,
        NULL,
        FALSE,
        NULL,
        'BHTN',
        'Bảo hiểm thất nghiệp',
        'INSURANCE',
        FALSE,
        FALSE,
        NULL,
        1.0000,
        'DEDUCTION',
        'ACTIVE'
    ),
    (
        NOW(6),
        NOW(6),
        'SYSTEM',
        'SYSTEM',
        0,
        NULL,
        FALSE,
        NULL,
        'CONG_DOAN_PHI',
        'Công đoàn phí',
        'DEDUCTION',
        FALSE,
        FALSE,
        NULL,
        1.0000,
        'DEDUCTION',
        'ACTIVE'
    ),
    (
        NOW(6),
        NOW(6),
        'SYSTEM',
        'SYSTEM',
        0,
        NULL,
        FALSE,
        NULL,
        'TAM_UNG',
        'Tạm ứng',
        'DEDUCTION',
        FALSE,
        FALSE,
        0.00,
        NULL,
        'DEDUCTION',
        'INACTIVE'
    ),
    (
        NOW(6),
        NOW(6),
        'SYSTEM',
        'SYSTEM',
        0,
        NULL,
        FALSE,
        NULL,
        'PHAT',
        'Phạt',
        'DEDUCTION',
        FALSE,
        FALSE,
        0.00,
        NULL,
        'DEDUCTION',
        'INACTIVE'
    )
ON DUPLICATE KEY UPDATE
    updated_at = VALUES(updated_at),
    updated_by = VALUES(updated_by),
    type = VALUES(type),
    is_taxable = VALUES(is_taxable),
    is_insurable = VALUES(is_insurable),
    amount = VALUES(amount),
    rate_percent = VALUES(rate_percent),
    nature = VALUES(nature),
    status = VALUES(status);