CREATE TABLE IF NOT EXISTS one_on_one_meetings (
    id               BIGINT         NOT NULL AUTO_INCREMENT,
    manager_id       BIGINT         NOT NULL,
    manager_name     VARCHAR(150)   NULL,
    employee_id      BIGINT         NOT NULL,
    employee_name    VARCHAR(150)   NULL,
    meeting_date     DATE           NOT NULL,
    agenda           VARCHAR(500)   NULL,
    notes            TEXT           NULL,
    action_items     TEXT           NULL,
    next_meeting_date DATE          NULL,
    created_at       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by       VARCHAR(255)   NULL,
    updated_by       VARCHAR(255)   NULL,
    deleted_at       DATETIME       NULL,
    deleted_by       VARCHAR(255)   NULL,
    is_deleted       TINYINT(1)     NOT NULL DEFAULT 0,
    version          BIGINT         NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_oom_manager  (manager_id, is_deleted),
    INDEX idx_oom_employee (employee_id, is_deleted),
    INDEX idx_oom_date     (meeting_date, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
