export const PAYROLL_ADMIN_CONSTANTS = {
  TITLE: "Cấu hình chính sách lương",
  SUBTITLE:
    "Quản lý danh sách thành phần lương để phục vụ hệ thống tính lương.",
  BTN_CREATE: "Tạo mới",
  SEARCH_PLACEHOLDER: "Tìm kiếm mã hoặc tên...",
  TABLE: {
    CODE: "Mã",
    NAME: "Tên",
    TYPE: "Loại",
    TAXABLE: "Chịu thuế",
    INSURABLE: "Đóng BHXH",
    NATURE: "Tính chất",
    AMOUNT: "Số tiền",
    RATE: "Hệ số (%)",
    STATUS: "Trạng thái",
    ACTIONS: "Hành động",
  },
  MESSAGES: {
    CREATE_SUCCESS: "Tạo thành phần lương thành công",
    UPDATE_SUCCESS: "Cập nhật thành phần lương thành công",
    EMPTY: "Chưa có thành phần lương nào.",
    NOT_FOUND: "Không tìm thấy kết quả phù hợp.",
    LOADING: "Đang tải dữ liệu...",
  },
  MODAL: {
    TITLE_CREATE: "Tạo thành phần lương",
    TITLE_EDIT: "Cập nhật thành phần lương",
    LABEL_CODE: "Mã",
    LABEL_NAME: "Tên",
    LABEL_TYPE: "Loại",
    LABEL_NATURE: "Tính chất",
    LABEL_STATUS: "Trạng thái",
    LABEL_AMOUNT: "Số tiền (VND)",
    LABEL_RATE: "Hệ số / Phần trăm (%)",
    PLACEHOLDER_CODE: "VD: LUONG_CO_BAN",
    PLACEHOLDER_NAME: "VD: Lương cơ bản",
    PLACEHOLDER_AMOUNT: "VD: 500000",
    PLACEHOLDER_RATE: "VD: 8",
    HELPER_LOCK:
      "Tính chất được tự động khóa theo loại: Bảo hiểm → Khấu trừ, Thưởng → Thu nhập.",
    REQUIRED_MARK: "*",
  },
  VALIDATION: {
    CODE_REQUIRED: "Mã là bắt buộc",
    CODE_REGEX: /^[A-Z0-9_]+$/i,
    CODE_INVALID_FORMAT: "Mã chỉ được chứa chữ cái, số và dấu gạch dưới (_)",
    CODE_MAX_LENGTH: 50,
    CODE_TOO_LONG: "Mã không được vượt quá 50 ký tự",
    NAME_REQUIRED: "Tên là bắt buộc",
    NAME_MAX_LENGTH: 255,
    NAME_TOO_LONG: "Tên không được vượt quá 255 ký tự",
    AMOUNT_REQUIRED: "Số tiền là bắt buộc",
    AMOUNT_MIN: 0,
    AMOUNT_INVALID: "Số tiền không hợp lệ",
    RATE_REQUIRED: "Hệ số (%) là bắt buộc",
    RATE_MIN: 0,
    RATE_MAX: 100,
    RATE_INVALID: "Hệ số không hợp lệ (0-100)",
  },
  TYPE_LABELS: {
    BASE: "Lương cơ bản",
    ALLOWANCE: "Phụ cấp",
    COMMISSION: "Hoa hồng",
    BONUS: "Thưởng",
    DEDUCTION: "Khấu trừ",
    INSURANCE: "Bảo hiểm",
  },
  NATURE_LABELS: {
    INCOME: "Thu nhập",
    DEDUCTION: "Khấu trừ",
  },
  STATUS_LABELS: {
    ACTIVE: "Đang áp dụng",
    INACTIVE: "Ngừng áp dụng",
  },
};

export const PAYROLL_HR_CONSTANTS = {
  TITLE: "Quản lý kỳ lương",
  SUBTITLE: "Thực hiện tính toán lương, BHXH, BHYT cho nhân viên trong kỳ.",
  LABEL_PERIOD: "Kỳ lương",
  BTN_RUN: "Run Payroll",
  BTN_RECALCULATE: "Tính lại",
  DESC_RUN:
    "Tự động tính BHXH, BHYT, BHTN và lương net cho toàn bộ nhân viên trong kỳ lương được chọn.",
  CARD_TITLE: "Thực hiện tính lương",
  SUMMARY_SUCCESS: "Tính lương thành công — kỳ",
  LABEL_PROCESSED: "Nhân viên đã tính",
  LABEL_TOTAL_NET: "Tổng lương net",
  LABEL_SKIPPED: "nhân viên bị bỏ qua do chưa có bản ghi lương.",
  NOTE_TITLE: "Lưu ý quan trọng",
  NOTES: [
    "Vui lòng chốt bảng công trước khi thực hiện chạy tính lương.",
    "Dữ liệu bảo hiểm và thuế TNCN sẽ được tính dựa trên cấu hình chính sách hiện hành.",
    'Nếu có thay đổi về hệ số lương trong kỳ, hãy sử dụng tính năng "Tính lại".',
  ],
  MESSAGES: {
    RUN_SUCCESS: (period: string) => `Tính lương kỳ ${period} thành công`,
    RECALC_SUCCESS: (period: string) =>
      `Tính lại lương kỳ ${period} thành công`,
    RUNNING: "Đang tính lương…",
    RECALCULATING: "Đang tính lại…",
    ERROR_DEFAULT: "Có lỗi xảy ra. Vui lòng thử lại.",
    ERROR_PERIOD_INVALID: "Kỳ lương không hợp lệ. Ví dụ đúng: 2026-03",
    EXPORT_SUCCESS: (period: string) =>
      `Đang tải xuống bảng lương kỳ ${period}...`,
    EXPORT_ERROR: "Xuất CSV thất bại. Vui lòng thử lại.",
    FETCH_ERROR: "Không thể tải dữ liệu kỳ này. Vui lòng thử lại.",
    EMPTY_DATA: (period: string) =>
      `Chưa có dữ liệu lương cho kỳ ${period}. Hãy chạy Run Payroll trước.`,
  },
  VIEW: {
    TITLE: "Bảng lương theo kỳ",
    SUBTITLE: "Xem và xuất file bảng lương toàn bộ nhân viên theo kỳ.",
    LABEL_PERIOD: "Kỳ lương",
    BTN_SEARCH: "Xem bảng lương",
    BTN_EXPORT: "Xuất CSV",
    EXPORTING: "Đang xuất...",
    TABLE: {
      EMP_CODE: "Mã NV",
      NAME: "Họ tên",
      DEPT: "Phòng ban",
      BASIC: "Lương CB",
      ALLOWANCE: "Phụ cấp",
      DEDUCTION: "Khấu trừ BH",
      NET: "Thực lĩnh",
      STATUS: "Trạng thái",
    },
    STATUS_LABELS: {
      DRAFT: "Nháp",
      CANCELLED: "Đã huỷ",
    },
    SUMMARY: {
      LABEL_EMPLOYEES: "Nhân viên:",
      LABEL_TOTAL_NET: "Tổng thực lĩnh:",
    },
    PAGINATION: {
      SHOW: "Hiển thị",
      TO: "–",
      ON_TOTAL: "trên tổng số",
      UNIT_EMP: "nhân viên",
    },
    DEFAULT_PAGE_SIZE: 10,
    PERIOD_REGEX: /^\d{4}-\d{2}$/,
  },
};
