export const AUTH_ROLES = {
  ADMIN: "ROLE_ADMIN",
  HR: "ROLE_HR",
  MANAGER: "ROLE_MANAGER",
  EMPLOYEE: "ROLE_EMPLOYEE",
} as const;

export const ROUTE_ROLE_GROUPS = {
  ADMIN_HR_MANAGER: [AUTH_ROLES.ADMIN, AUTH_ROLES.HR, AUTH_ROLES.MANAGER],
  ALL_AUTHENTICATED: [
    AUTH_ROLES.ADMIN,
    AUTH_ROLES.HR,
    AUTH_ROLES.MANAGER,
    AUTH_ROLES.EMPLOYEE,
  ],
  EMPLOYEE_HR_MANAGER: [AUTH_ROLES.EMPLOYEE, AUTH_ROLES.HR, AUTH_ROLES.MANAGER],
};
